# Generated by Django 4.2.11 on 2024-07-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_birthplace_item_bloodtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bloodtype',
            new_name='place_of_birth',
        ),
    ]
